### ISSUE TITLE
BUG @command responds to messages containing the command

### ISSUE THREAD

**Issue by jhaisley** [DonDebonair/slack-machine#1047]
@command responds to messages containing the command.

For example:
@channel check out /cool-feature when you have time, I just added it to the bot.

Slack-Machine Bot[APP]
Does something amazing.

**Comment by jhaisley** [comment]
I was going to fix this myself, however after quite a few attempts I can't make it happen again. Closing for now.

**Comment by DonDebonair** [comment]
Im pretty sure that this bug is impossible to occur. The events for messages and slash commands are completely different. 

Should you run into it anyways, let me know
