### ISSUE TITLE
Start and message to group DM

### ISSUE THREAD

**Issue by jingwei99** [DonDebonair/slack-machine#1101]
Hey @DonDebonair 👋 

I was building a slack bot for a workspace and stumbled upon `slack-machine`, it's really easy to work with, appreciate the work! 

For what I was doing, I needed a function to start and DM to a group of users, so I added the function locally on my machine (in base.py and slack.py), the function is working well. Would it be ok with you if I clean the changes up and put it up for review to get it added into the repo? lmk!

**Comment by DonDebonair** [comment]
Hey @jingwei99 , I somehow missed the issue you opened. For sure I would welcome a PR!

**Comment by jingwei99** [comment]
@DonDebonair Nice! Thanks for the follow up, and sry for dropping the ball on my end - workload picked up.

**Comment by DonDebonair** [comment]
No worries! Life can be like that. Glad it worked out in the end!

Should you have any other ideas for Slack Machine, don't hesitate to bring it up!
