### ISSUE TITLE
Run as a systemd service

### ISSUE THREAD

**Issue by jhaisley** [DonDebonair/slack-machine#1147]
There should be support for running as a systemd service.  

I believe this will be somewhat easy to do using the simple service type.

**Comment by DonDebonair** [comment]
I don't have use for this personally, as I run my Slack bots built with Slack Machine inside Docker containers. But I can totally see how this would be useful to others. Given that I cannot reasonably test this, I also cannot really build this. But I'm open to a PR that implements SystemD support.

**Comment by DonDebonair** [comment]
I'm closing this for now. You are welcome to open a PR of course!
