### ISSUE TITLE
Feature request extend storage to sqlite or postgres db

### ISSUE THREAD

**Issue by dorel14** [DonDebonair/slack-machine#145]
Hello
I'd like to extend storage so that i can use postgres db aon sqlite db , Can you help me in making this ?

Thx

**Comment by dorel14** [comment]
Made it myself on sqlite 
bye

**Comment by DandyDev** [comment]
Eeeeh, why don't you share your code by opening a pull request? So other people can enjoy it as well...

**Comment by dorel14** [comment]
when finished and tested , i will share my plugin to connect to sqlite or postgres

**Comment by dorel14** [comment]
Hello , i don't know how send a pull request , here's my code to add postgres db to my plugins
I added peewee ,  psycopg2 , configparser because i haven't succeeded in using your settings system

 pip install peewee 
 pip install psycopg2
pip install configparser

[config.txt](https://github.com/DandyDev/slack-machine/files/2933254/config.txt)
here is my an example of a model.py to initialise some tables 

[models.txt](https://github.com/DandyDev/slack-machine/files/2933261/models.txt)

when i want to use my models in a plugin , here is an example

`from peewee import *
from plugins.helpers.models import *
from machine.plugins.base import MachineBasePlugin
from machine.plugins.decorators import respond_to


class gestionDB(MachineBasePlugin):
    """gestionDB: Plugin de gestion de la base de donnée"""

    @respond_to(r"^Creer table")
    def creationTableDb(self, msg):
        """Creer table: Cette fonction permet de créer les tables de bdd"""
        pg_db.connect()
        pg_db.create_tables(
            [astreinte, permananceSamedi, meteoService, evenements])
        msg.reply("Tables créées")`


and another one 
`from machine.plugins.base import MachineBasePlugin
from machine.plugins.decorators import schedule
from machine.plugins.decorators import listen_to
from plugins.helpers.models import *
from datetime import datetime, timedelta
import re

format_str = '%d/%m/%Y'


class Astreinte(MachineBasePlugin):
    """Astreinte: Ce plugins sert à gérer les astreintes dans Grafana"""
    @schedule(day_of_week='mon', hour='22', minute='55')
    def QuiAstreinte(self):
        """Tache planifiée: Demande dans la chaine intégration qui est d'astreinte"""
        self.say('integration',
                 "Bonjour qui est d'astreinte cette semaine ")

    @listen_to(r"ajout astreinte:")
    def ajoutAstreinte(self, msg):
astreinte.add(personne, quandAstreinte[1], qui, maintenant)`
