### ISSUE TITLE
listen to only message

### ISSUE THREAD

**Issue by hyowoo** [DonDebonair/slack-machine#214]
thx for greate machine.
i really appreciate.
but i have one issue.

ex)
///
@listen_to('')
def to_duty(message):
    print(message)
....

i want only listen_to NEW MESSAGE, NOT THREAD.
how can i solve this problem?

**Comment by davidolrik** [comment]
You can't do it via the api, but you can look for `thread_ts` in the internal message event object like so:

```python
if 'thread_ts' in msg._msg_event;
    # Do your stuff here
    pass
```

I have created a pull request #286 with this feature.
