### ISSUE TITLE
Reacting to Bots and Apps

### ISSUE THREAD

**Issue by vanadisv** [DonDebonair/slack-machine#40]
The slack-machine bot doesn't seem to react to apps and/or bots currently.

How could I trigger the bot with bot/app generated messages?

**Comment by DandyDev** [comment]
Can you give an example of your setup that has messages that slack-machine doesn't react to? That way, I can try to reproduce.

**Comment by vanadisv** [comment]
Hello @DandyDev, thanks for your reply!

I tried this with a simple IFTTT workflow that basically posts the content of received emails in a Slack channel.

If I setup slack-machine to listen_to/respond_to certain keywords (say, "hello"), slack-machine will react if I posted that message directly into the channel.

However, slack-machine doesn't react if IFTTT posted the content of an email containing the same word "hello".

**Comment by DandyDev** [comment]
Thanks for the clarification, that should be something I can replicate. I will look into it!

**Comment by kb18951452** [comment]
Is this still an issue?

**Comment by wietze** [comment]
I believe this might be related to how users are looked up ([machine/slack.py L17-L19](https://github.com/DandyDev/slack-machine/blob/master/machine/slack.py#L17-L19)) e.g. when using `.reply()`. If the sending user is a bot, it might not appear in `self.users`.
