### ISSUE TITLE
How do I set my bot user's icon?

### ISSUE THREAD

**Issue by MattF-NSIDC** [DonDebonair/slack-machine#643]
I thought this was something I could set in the slack App's configuration, but I was only able to find a setting for display name, and my app is showing up with the default silhouette icon. Is there a way to configure this that I'm missing?

Thank you!

**Comment by DonDebonair** [comment]
Hey @MattF-NSIDC ! You _can_ actually set the app icon (which will also serve as bot icon) in the app configuration:

1. Go to the [list of apps](https://api.slack.com/apps) for your workspace
2. Click on the app you want to change the icon for
3. Go to _Display Information_. Here you can upload an app icon
![image](https://user-images.githubusercontent.com/854991/193346399-0c8aed24-c9c3-4847-b023-b162ad6f2a95.png)

Hope this helps!

**Comment by MattF-NSIDC** [comment]
Wonderful, thank you :bow:  I was confused by the separate section for editing the bot's display name.
