### ISSUE TITLE
Can't change log level and use slack-machine logger

### ISSUE THREAD

**Issue by pawelros** [DonDebonair/slack-machine#730]
Hey, first of all thanks a lot for your great work on the project!

I carefully read the docs and tried to:
- change the log level to DEBUG by setting `LOGLEVEL=DEBUG`  environment variable
- use loggers provided by Slack Machine in my handler functions.

None of it works:
- whatever I do application prints only INFO and ERROR messages from slack-machine.
- logger injected to my message handler prints only ERROR messages.

Am I doing something wrong?

```
❯ echo $LOGLEVEL
DEBUG

``` 

handler:

```
    @listen_to(regex=r"(password.*reset)|(reset.*password)")
    async def question(self, msg, logger):
        print(logger.level) # prints 0 (NOT_SET)
        logger.info("my_handler invoked!") # not printed
        logger.debug("debug my_handler invoked!") # not printed
        logger.error("error my_handler invoked!") # OK
```

app run:

```
❯ slack-machine
2023-03-01 11:06:06 [info     ] Initializing Slack Machine...
2023-03-01 11:06:06 [info     ] Loading settings...
2023-03-01 11:06:06 [info     ] Settings loaded!
0
2023-03-01T10:06:29.070461Z [error    ] error my_handler invoked!      [my_bot.plugins.password_reset:PasswordReset.question] filename=password_reset.py func_name=question lineno=14 user_id=<redacted> user_name=<redacted>
```

**Comment by DonDebonair** [comment]
I didn't read your initial report properly. You made a mistake by setting the `LOGLEVEL` _environment variable_. The way to set the log level is to set `LOGLEVEL` in your `local_settings.py` _or_ to set the `SM_LOGLEVEL` environment variable.
